version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: apps/back/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
